import Combine
import SwiftUI

/// One setting as it appears in ~/.notchnull/settings.json: "look.accent", its type and range,
/// how to read it from Preferences and how to apply a value (returning an error message).
struct SettingField {
    let key: String
    let type: String
    let summary: String
    let read: @MainActor (Preferences) -> JSONValue
    let write: @MainActor (Preferences, JSONValue) -> String?
}

/// Keeps ~/.notchnull/settings.json and the app's settings the same, in both directions: edit
/// the file and the notch changes live; change a setting in the app and the file is rewritten.
@MainActor
final class SettingsFile: ObservableObject {
    static let shared = SettingsFile()

    /// Problems in the last file read (unknown keys, wrong types), shown in Settings and status.json.
    @Published private(set) var errors: [String] = []

    private var lastWritten: Data?
    private var watcher: FileWatcher?
    private var cancellables: Set<AnyCancellable> = []
    private let preferences = Preferences.shared

    func start() {
        NotchHome.writeIfChanged(Self.reference, to: NotchHome.settingsReference)
        if let data = try? Data(contentsOf: NotchHome.settings) {
            apply(data)
        }
        write()
        preferences.objectWillChange
            .debounce(for: .milliseconds(400), scheduler: RunLoop.main)
            .sink { [weak self] _ in self?.write() }
            .store(in: &cancellables)
        let watcher = FileWatcher(paths: [NotchHome.root]) { [weak self] paths in
            guard paths.contains(where: { $0.hasSuffix("/settings.json") }) else { return }
            MainActor.assumeIsolated { self?.fileChanged() }
        }
        watcher.start()
        self.watcher = watcher
    }

    private func fileChanged() {
        guard let data = try? Data(contentsOf: NotchHome.settings), data != lastWritten else { return }
        apply(data)
    }

    /// Applies settings. Only values that differ are set, and each field validates its own value,
    /// so one bad line never blocks the rest. Problems in the file itself are kept in `errors`;
    /// a patch from the CLI or API only returns its problems, since the file does not hold them.
    @discardableResult
    func apply(_ data: Data, isPatch: Bool = false) -> [String] {
        guard let root = JSONValue.parse(data), let sections = root.object else {
            let problem = isPatch ? "The patch is not a JSON object." : "settings.json is not a JSON object. Nothing was applied; fix the syntax and save again."
            if !isPatch {
                errors = [problem]
                NotchStatus.write()
            }
            return [problem]
        }
        var problems: [String] = []
        let known = Set(Self.fields.map(\.key))
        for (section, value) in sections {
            guard let entries = value.object else {
                problems.append("\"\(section)\" should be an object of settings.")
                continue
            }
            for key in entries.keys where !known.contains("\(section).\(key)") {
                problems.append("Unknown setting \(section).\(key). See settings.reference.md.")
            }
        }
        withAnimation(Motion.state) {
            for field in Self.fields {
                guard let value = root.value(at: field.key), value != field.read(preferences) else { continue }
                if let problem = field.write(preferences, value) { problems.append("\(field.key): \(problem)") }
            }
        }
        if !isPatch {
            errors = problems
            NotchStatus.write()
        }
        if !problems.isEmpty { Log.app.notice("settings \(isPatch ? "patch" : "file"): \(problems.count) problem(s)") }
        return problems
    }

    /// The current settings as the file shows them, grouped by section.
    func snapshot() -> JSONValue {
        var sections: [String: [String: JSONValue]] = [:]
        for field in Self.fields {
            let parts = field.key.split(separator: ".", maxSplits: 1).map(String.init)
            sections[parts[0], default: [:]][parts[1]] = field.read(preferences)
        }
        return .object(sections.mapValues { .object($0) })
    }

    private func write() {
        guard let data = try? JSONSerialization.data(withJSONObject: snapshot().any, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]) else { return }
        guard data != lastWritten, (try? Data(contentsOf: NotchHome.settings)) != data else {
            lastWritten = data
            return
        }
        lastWritten = data
        try? data.write(to: NotchHome.settings, options: .atomic)
    }

    // MARK: Reference

    static var reference: String {
        var lines = [
            "# settings.json reference",
            "",
            "Generated by NotchNull \(Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "dev"). Edit ~/.notchnull/settings.json; changes apply as soon as the file is saved. Unknown keys and bad values are reported in ~/.notchnull/status.json and in Settings › Build.",
            "",
            "| Key | Type | What it does |",
            "|---|---|---|",
        ]
        lines += fields.map { "| `\($0.key)` | \($0.type) | \($0.summary) |" }
        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: Fields

    static let fields: [SettingField] = look + size + island + motion + behavior + features + composition + files

    private static let look: [SettingField] = [
        choice("look.body", "Body material.", \.bodyStyle),
        color("look.tint", "Body color when look.body is \"tinted\".", \.tintHex),
        color("look.accent", "Accent for the selected tab, toggles and sliders.", \.accentHex),
        bool("look.accentFollowsMac", "Use the macOS accent color instead of look.accent.", \.accentFollowsSystem),
        choice("look.shape", "\"auto\" floats an island on screens without a hardware notch; \"notch\" or \"island\" force one.", \.shapeStyle),
        number("look.opacity", "Body opacity.", \.bodyOpacity, Preferences.Limits.bodyOpacity),
        number("look.roundness", "Corner radius scale.", \.cornerScale, Preferences.Limits.cornerScale),
        bool("look.shadow", "Shadow under the open panel.", \.shadow),
        bool("look.emissionEdge", "Soft light along the bottom edge tinted by the activity.", \.emissionEdge),
        number("look.emissionIntensity", "Strength of the emission edge.", \.emissionIntensity, 0.2...1),
        bool("look.glowNeedsYou", "Light runs around the outline while an agent needs you.", \.glowNeedsYou),
        bool("look.hideHardwareNotch", "Paint the menu bar black so the camera housing disappears.", \.hideNotch),
    ]

    private static let size: [SettingField] = [
        number("size.notchExtraWidth", "Points added to the closed notch (it can only grow).", \.closedExtraWidth, Preferences.Limits.closedExtraWidth),
        number("size.wings", "Scale of wings and banners beside the notch.", \.activityWidthScale, Preferences.Limits.activityWidthScale),
        number("size.panelWidth", "Open panel width in points.", \.panelWidth, Preferences.Limits.panelWidth),
        number("size.panelHeight", "Open panel content height in points.", \.panelHeight, Preferences.Limits.panelHeight),
    ]

    private static let island: [SettingField] = [
        choice("island.content", "What the idle island shows.", \.pillContent),
        bool("island.clock24h", "24-hour clock in the island.", \.use24Hour),
        bool("island.satellites", "Small circles beside the island for media and controls.", \.islandSatellites),
        number("island.width", "Idle island width in points; 0 fits what it shows.", \.islandWidth, Preferences.Limits.islandWidth),
        number("island.height", "Island height in points; 0 fits it inside the menu bar.", \.islandHeight, Preferences.Limits.islandHeight),
        number("island.top", "Gap between the top of the screen and the island.", \.islandTop, Preferences.Limits.islandTop),
    ]

    private static let motion: [SettingField] = [
        number("motion.speed", "Animation speed; 2 is instant.", \.animationSpeed, 0.5...2),
        number("motion.bounce", "Spring bounce when opening.", \.bounce, 0...0.4),
        number("motion.hoverDelay", "Seconds of hover before the panel opens.", \.hoverDelay, 0...0.5),
        number("motion.closeDelay", "Seconds after the pointer leaves before it closes.", \.closeDelay, 0.05...1.2),
        bool("motion.cascade", "Rows arrive one after another.", \.staggerContent),
        bool("motion.swipeTabs", "Swipe left or right on the open panel to switch tabs.", \.tabSwipeEnabled),
        choice("motion.openOn", "Open on hover or click.", \.openTrigger),
    ]

    private static let behavior: [SettingField] = [
        choice("behavior.display", "Which displays get a notch. Selected uses behavior.selectedDisplays.", \.displayMode),
        SettingField(
            key: "behavior.selectedDisplays", type: "list of display UUIDs", summary: "Displays enabled in Selected mode. IDs are listed in status.displays and survive reconnects. An empty list hides every panel.",
            read: { .array($0.selectedDisplays.map { .string($0) }) },
            write: { prefs, value in
                guard let entries = value.array, entries.allSatisfy({ $0.string.flatMap(UUID.init(uuidString:)) != nil }) else {
                    return "expected a list of display UUIDs"
                }
                prefs.selectedDisplays = Array(Set(entries.compactMap(\.string).map { $0.uppercased() })).sorted()
                return nil
            }
        ),
        bool("behavior.hideOnFullscreen", "Hide the notch on a display while a fullscreen app covers it.", \.hideOnFullscreen),
        bool("behavior.checkForUpdates", "Ask GitHub once a day whether a newer NotchNull exists.", \.checkForUpdates),
        bool("behavior.haptics", "Haptic tap when opening.", \.haptics),
        bool("behavior.sounds", "Timer chime and meeting reminder.", \.sounds),
        bool("behavior.menuBarIcon", "Show the menu bar icon.", \.showMenuBarIcon),
        bool("behavior.sayHello", "Handwritten hello at launch and unlock.", \.sayHello),
        bool("behavior.paceWarnings", "Warn when your pace would use a limit up before it resets.", \.paceWarnings),
        bool("behavior.usageShowsRemaining", "Show limits as % left instead of % used.", \.usageShowsRemaining),
        SettingField(
            key: "behavior.clipboardShortcut", type: "string or null", summary: "Global shortcut for Clipboard, like \"ctrl+cmd+v\"; null turns it off.",
            read: { $0.clipboardShortcut.map { .string($0.string) } ?? .null },
            write: { prefs, value in
                if value == .null { prefs.clipboardShortcut = nil; return nil }
                guard let text = value.string, let shortcut = KeyShortcut(string: text) else { return "use modifiers and one key, like \"ctrl+cmd+v\"" }
                prefs.clipboardShortcut = shortcut
                return nil
            }
        ),
    ]

    private static let features: [SettingField] = [
        bool("features.music", "Now playing.", \.musicEnabled),
        bool("features.musicWings", "Album art and beat beside the notch.", \.musicWings),
        bool("features.hud", "Volume and brightness HUD.", \.hudEnabled),
        bool("features.replaceSystemHUD", "Handle media keys instead of the system HUD (needs Accessibility).", \.replaceSystemHUD),
        bool("features.tray", "File Tray and drop targets.", \.trayEnabled),
        bool("features.clipboard", "Clipboard history.", \.clipboardEnabled),
        bool("features.screenshots", "New screenshots wait in the Tray.", \.screenshotsEnabled),
        bool("features.downloads", "Download progress.", \.downloadsEnabled),
        bool("features.battery", "Charging and low battery.", \.batteryEnabled),
        bool("features.devices", "Devices and connections.", \.accessoriesEnabled),
        bool("features.meetings", "Meeting countdowns.", \.calendarEnabled),
        bool("features.agents", "Claude Code, Codex and opencode sessions.", \.agentsEnabled),
        bool("features.codex", "Watch Codex sessions and limits.", \.codexEnabled),
        bool("features.opencode", "Watch opencode sessions and tokens.", \.opencodeEnabled),
        bool("features.claudeUsage", "Claude usage limits.", \.claudeUsageEnabled),
        bool("features.plans", "Limits of other coding plans found on this Mac (GLM, Kimi, MiniMax, OpenCode Go, Copilot).", \.planUsageEnabled),
        bool("features.agentWings", "Running time beside the notch.", \.agentWings),
        choice("motion.agentMark", "How an agent's logo moves while it works: still, spin, pulse or shimmer.", \.agentMarkMotion),
        bool("features.mirror", "Camera mirror tab.", \.mirrorEnabled),
        bool("features.stats", "CPU and memory.", \.statsEnabled),
    ]

    private static let composition: [SettingField] = [
        strings("tabs.order", "Tab order: \(NotchTab.allCases.map(\.rawValue).joined(separator: ", ")).", \.tabOrder, allowed: NotchTab.allCases.map(\.rawValue)),
        SettingField(
            key: "tabs.hidden", type: "list of tab names", summary: "Tabs to hide (home cannot be hidden).",
            read: { .array($0.hiddenTabs.sorted().map { .string($0) }) },
            write: { prefs, value in
                guard let names = value.array?.compactMap(\.string) else { return "expected a list of tab names" }
                prefs.hiddenTabs = Set(names.filter { $0 != NotchTab.home.rawValue })
                return names.first { NotchTab(rawValue: $0) == nil }.map { "unknown tab \($0)" }
            }
        ),
        strings("home.rows", "Home rows in order: \(Preferences.HomeRow.allCases.map(\.rawValue).joined(separator: ", ")).", \.homeRows, allowed: Preferences.HomeRow.allCases.map(\.rawValue)),
        SettingField(
            key: "activities.disabled", type: "list of names", summary: "Activities that never slide out: \(ActivityKind.allCases.map(\.name).joined(separator: ", ")).",
            read: { .array($0.disabledActivities.sorted().map { .string($0) }) },
            write: { prefs, value in
                guard let names = value.array?.compactMap(\.string) else { return "expected a list of activity names" }
                prefs.disabledActivities = Set(names)
                ActivityCenter.shared.refresh()
                let valid = Set(ActivityKind.allCases.map(\.name))
                return names.first { !valid.contains($0) }.map { "unknown activity \($0)" }
            }
        ),
    ]

    private static let files: [SettingField] = [
        bool("downloads.cleanup", "Ask how long to keep new downloads, then trash them when time is up.", \.downloadCleanupEnabled),
        choice("downloads.defaultStop", "Stop highlighted when the notch asks.", \.downloadDefaultChoice),
        bool("downloads.useDefaultWhenUnanswered", "Unanswered: true uses the highlighted stop, false keeps the file.", \.downloadUnansweredUsesDefault),
        bool("downloads.tagTemporary", "Tag counting-down files as Temporary in Finder.", \.downloadTagTemporary),
        SettingField(
            key: "downloads.rules", type: "object ext → stop", summary: "Answers remembered by extension, like {\"dmg\": \"day\"}. Stops: \(KeepChoice.allCases.map(\.rawValue).joined(separator: ", ")).",
            read: { .object($0.downloadRules.mapValues { .string($0) }) },
            write: { prefs, value in
                guard let entries = value.object else { return "expected an object like {\"dmg\": \"day\"}" }
                var rules: [String: String] = [:]
                var problem: String?
                for (ext, stop) in entries {
                    if let stop = stop.string, KeepChoice(rawValue: stop) != nil { rules[ext.lowercased()] = stop } else { problem = "\(ext) has an unknown stop" }
                }
                prefs.downloadRules = rules
                return problem
            }
        ),
    ]

    // MARK: Field builders

    private static func bool(_ key: String, _ summary: String, _ path: ReferenceWritableKeyPath<Preferences, Bool>) -> SettingField {
        SettingField(key: key, type: "true / false", summary: summary, read: { .bool($0[keyPath: path]) }, write: { prefs, value in
            guard let bool = value.bool else { return "expected true or false" }
            prefs[keyPath: path] = bool
            return nil
        })
    }

    private static func number(_ key: String, _ summary: String, _ path: ReferenceWritableKeyPath<Preferences, Double>, _ range: ClosedRange<Double>) -> SettingField {
        SettingField(key: key, type: "number \(format(range.lowerBound))–\(format(range.upperBound))", summary: summary, read: { .number(($0[keyPath: path] * 1000).rounded() / 1000) }, write: { prefs, value in
            guard let number = value.double else { return "expected a number" }
            prefs[keyPath: path] = min(max(number, range.lowerBound), range.upperBound)
            return range.contains(number) ? nil : "\(format(number)) is outside \(format(range.lowerBound))–\(format(range.upperBound)); clamped"
        })
    }

    private static func choice<Value: RawRepresentable & CaseIterable>(_ key: String, _ summary: String, _ path: ReferenceWritableKeyPath<Preferences, Value>) -> SettingField where Value.RawValue == String {
        let options = Value.allCases.map(\.rawValue)
        return SettingField(key: key, type: options.map { "\"\($0)\"" }.joined(separator: " / "), summary: summary, read: { .string($0[keyPath: path].rawValue) }, write: { prefs, value in
            guard let raw = value.string, let option = Value(rawValue: raw) else { return "expected one of \(options.joined(separator: ", "))" }
            prefs[keyPath: path] = option
            return nil
        })
    }

    private static func color(_ key: String, _ summary: String, _ path: ReferenceWritableKeyPath<Preferences, Int>) -> SettingField {
        SettingField(key: key, type: "\"#RRGGBB\"", summary: summary, read: { .string(String(format: "#%06X", $0[keyPath: path])) }, write: { prefs, value in
            guard let text = value.string, let hex = Int(text.trimmingCharacters(in: CharacterSet(charactersIn: "# ")), radix: 16), text.filter(\.isHexDigit).count == 6 else {
                return "expected a color like \"#3DDBB0\""
            }
            prefs[keyPath: path] = hex
            return nil
        })
    }

    private static func strings(_ key: String, _ summary: String, _ path: ReferenceWritableKeyPath<Preferences, [String]>, allowed: [String]) -> SettingField {
        SettingField(key: key, type: "list of names", summary: summary, read: { .array($0[keyPath: path].map { .string($0) }) }, write: { prefs, value in
            guard let names = value.array?.compactMap(\.string) else { return "expected a list of names" }
            prefs[keyPath: path] = names.filter(allowed.contains)
            return names.first { !allowed.contains($0) }.map { "unknown name \($0)" }
        })
    }

    private static func format(_ value: Double) -> String {
        value.rounded() == value ? String(Int(value)) : String(format: "%g", value)
    }
}
